version: '3'

volumes:
    datafiles:

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        volumes:
            - datafiles:/var/lib/mssql
        restart: always
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Secret7+"
        ports:
            - "4444:1433"
        networks:
            - customers-app
    customers-api:
        image: jvalos/customers-api
        depends_on: 
            - mssql
        restart: unless-stopped
        environment: 
            DBHost: "host.docker.internal"
            DBPort: "4444"
            DBUser: "SA"
            DBPassword: "Secret7+"
            Database: "Customers"
        ports:
            - "8080:80"
        networks:
            - customers-app
    react-frontend:
        image: jvalos/customers-app
        stdin_open: true
        tty: true
        depends_on: 
            - customers-api
        ports: 
            - "8000:80"
        networks:
            - customers-app
networks:
    customers-app:
        driver: bridge
